project:
  type: website
  output-dir: _site

metadata-files:
  - ../classlib/quarto/website/hickernell-website.yml
  - ../classlib/quarto/metadata/hickernell-texts.yml

website:
  title: "Fred J. Hickernell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks.qmd
        text: Talks
      - href: courses.qmd
        text: Courses
      - href: software.qmd
        text: Software
      - href: papers.qmd
        text: Papers
  page-footer:
    center: |
      Created by Fred J. Hickernell with assistance from ChatGPT.

format:
  html:
    css:
      - ../classlib/quarto/website/hickernell-website.css
    include-in-header:
      - ../classlib/quarto/slides/hickernell-latex-macros.js
    link-external-newwindow: true
    toc: true
    toc-depth: 3